CREATE SCHEMA E_COMMERCE;

CREATE TABLE CLIENTE(
COD_CLIENTE VARCHAR(100) NOT NULL,
TELEFONE_1 VARCHAR(14) NOT NULL,
TELEFONE_2 VARCHAR(14),
EMAIL VARCHAR(30) NOT NULL,
RUA VARCHAR(20) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
CIDADE VARCHAR(20) NOT NULL,
ESTADO VARCHAR(20) NOT NULL,

PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE PESSOA_FISICA(
COD_CLIENTE VARCHAR(100) NOT NULL,
RG VARCHAR(20) NOT NULL,
CPF VARCHAR(20) NOT NULL
);

CREATE TABLE PESSOA_JURIDICA(
COD_CLIENTE VARCHAR(100) NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
IE VARCHAR(20) NOT NULL
);

CREATE TABLE PEDIDO(
COD_CLIENTE VARCHAR(100) NOT NULL,
COD_PEDIDO VARCHAR(100) NOT NULL,
DATA DATE NOT NULL,
VALOR VARCHAR(20) NOT NULL,

PRIMARY KEY (COD_PEDIDO)
);

CREATE TABLE ITENS_PEDIDO(
COD_LIVRO VARCHAR(20) NOT NULL,
COD_PEDIDO VARCHAR(100) NOT NULL,
QNTD_PEDIDO VARCHAR(10),
VALOR_ITEM VARCHAR(20)
);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_ITENS_PEDIDO_PEDIDO
FOREIGN KEY (COD_PEDIDO)
REFERENCES PEDIDO (COD_PEDIDO);

CREATE TABLE LIVRO(
COD_EDITORA VARCHAR(20) NOT NULL,
COD_LIVRO VARCHAR(20) NOT NULL,
NOME_LIVRO VARCHAR(100) NOT NULL,
ANO_PUBLICACAO INTEGER NOT NULL,
CATEGORIA VARCHAR(20) NOT NULL,
TITULO VARCHAR(100) NOT NULL,
ISBN VARCHAR(30) NOT NULL,
AUTOR VARCHAR(50) NOT NULL,

PRIMARY KEY (COD_LIVRO)
);

CREATE TABLE EDITORA(
COD_EDITORA VARCHAR(20) NOT NULL,
TELEFONE_1 VARCHAR(14) NOT NULL,
TELEFONE_2 VARCHAR(14),
EMAIL VARCHAR(50) NOT NULL,
NOME_CONTATO VARCHAR(50) NOT NULL,

PRIMARY KEY (COD_EDITORA)
);

CREATE TABLE ESTOQUE(
COD_LIVRO VARCHAR(20) NOT NULL,
QNTD_ESTOQUE INTEGER NOT NULL
);

ALTER TABLE PESSOA_FISICA ADD CONSTRAINT FK_PESSOA_FISICA_CLIENTE
FOREIGN KEY (COD_CLIENTE)
REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE PESSOA_FISICA ADD CONSTRAINT FK_PESSOA_JURIDICA_CLIENTE
FOREIGN KEY (COD_CLIENTE)
REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_CLIENTE
FOREIGN KEY (COD_CLIENTE)
REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_ITENS_PEDIDO_PEDIDO
FOREIGN KEY (COD_PEDIDO)
REFERENCES PEDIDO (COD_PEDIDO);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_ITENS_PEDIDO_LIVRO
FOREIGN KEY (COD_LIVRO)
REFERENCES LIVRO (COD_LIVRO);

ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_EDITORA
FOREIGN KEY (COD_EDITORA)
REFERENCES EDITORA (COD_EDITORA);

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_LIVRO
FOREIGN KEY (COD_LIVRO)
REFERENCES LIVRO (COD_LIVRO);
